{{- if .Values.scMessenger.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.scMessenger.serviceAccount.metadata.name }}
  labels:
    app: {{ .Values.scMessenger.serviceAccount.metadata.labels.app }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.scMessenger.serviceAccount.metadata.annotations }}
{{- end }}
   