apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "scm-chart.fullname" . }}-service-account
  labels:
    app: scmessenger-staging
  {{- include "scm-chart.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.serviceAccount.serviceAccount.annotations | nindent 4 }}