apiVersion: v1
kind: Service
metadata:
  name: {{ include "scm-chart.fullname" . }}-service
  labels:
  {{- include "scm-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: scmessenger-staging
  {{- include "scm-chart.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.service.ports | toYaml | nindent 2 }}